[package]
name = "inference_profiles"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
aws-config = "1.6.3"
aws-sdk-bedrock = "1.90.0"
aws-sdk-costexplorer = "1.73.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_with = { version = "3.16.1", features = ["time_0_3"] }
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "time"] }
time = "0.3.47"
tracing = "0.1.44"
