[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
apikeys = { path = "../apikeys" }
axum = "0.8.1"
chat = { git = "https://github.com/llm-proxy-rs/llm-proxy-rs.git", version = "0.1.0" }
config = "0.15.11"
dotenv = "0.15.0"
handlers = { git = "https://github.com/llm-proxy-rs/cognito.git", version = "0.1.0" }
request = { git = "https://github.com/llm-proxy-rs/llm-proxy-rs.git", version = "0.1.0" }
reqwest = "0.12.14"
sqlx = { version = "0.8.3", features = ["postgres"] }
tokio = { version = "1.44.1", features = ["full"] }
tower-sessions = "0.14.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
users = { path = "../users" }
